# Generated by Django 2.2 on 2020-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_login_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='最后登录IP地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
    ]
